#!/usr/bin/python
# -*- coding:utf-8 -*-
# @author  : Liu Lijun
# @date    : 2026-08-29
# @description: V1 contract for VirtualCourt judge decisions.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import ConfigDict, Field, field_validator, model_validator

from .common import (
    CaseContext,
    CourtEvent,
    IntegrationModel,
    PartyRole,
    StageSummary,
)


class TriggerType(StrEnum):
    LEGAL_QUESTION = "LEGAL_QUESTION"
    CLARIFICATION_NEEDED = "CLARIFICATION_NEEDED"
    SUPPLEMENTARY_QUESTION_NEEDED = "SUPPLEMENTARY_QUESTION_NEEDED"
    OFF_TOPIC_OR_VERBOSE = "OFF_TOPIC_OR_VERBOSE"
    SUMMARY_REQUESTED = "SUMMARY_REQUESTED"
    STAGE_READY = "STAGE_READY"
    MANUAL_ASSIST = "MANUAL_ASSIST"


class ActionType(StrEnum):
    NO_ACTION = "NO_ACTION"
    ASK_PARTY = "ASK_PARTY"
    REQUEST_CLARIFICATION = "REQUEST_CLARIFICATION"
    SUMMARIZE = "SUMMARIZE"
    PAUSE_SESSION = "PAUSE_SESSION"
    RESUME_SESSION = "RESUME_SESSION"
    END_CURRENT_SPEECH = "END_CURRENT_SPEECH"
    END_CURRENT_STAGE = "END_CURRENT_STAGE"
    ADVANCE_STEP = "ADVANCE_STEP"
    ADJOURN = "ADJOURN"


class SpeechType(StrEnum):
    NONE = "NONE"
    QUESTION = "QUESTION"
    CLARIFICATION = "CLARIFICATION"
    SUMMARY = "SUMMARY"
    LEGAL_EXPLANATION = "LEGAL_EXPLANATION"
    PROCEDURAL_DIRECTION = "PROCEDURAL_DIRECTION"


class ConfidenceLevel(StrEnum):
    HIGH = "HIGH"
    LOW = "LOW"
    INSUFFICIENT = "INSUFFICIENT"


class IssueStatus(StrEnum):
    PENDING = "PENDING"
    IN_DEBATE = "IN_DEBATE"
    NEEDS_FURTHER_DEBATE = "NEEDS_FURTHER_DEBATE"
    CONFIRMED = "CONFIRMED"


class IssueAssessmentResult(StrEnum):
    NOT_APPLICABLE = "NOT_APPLICABLE"
    CONTINUE_DEBATE = "CONTINUE_DEBATE"
    READY_TO_CONFIRM = "READY_TO_CONFIRM"
    INSUFFICIENT_CONTEXT = "INSUFFICIENT_CONTEXT"


class JudgeOutputModel(IntegrationModel):
    """Strict base for JSON generated by the judge agent."""

    model_config = ConfigDict(
        extra="forbid",
        str_strip_whitespace=True,
        strict=True,
    )


IssueText = Annotated[str, Field(min_length=1, max_length=2000)]


class CourtIssue(IntegrationModel):
    issue_id: str = Field(min_length=1, max_length=64)
    question: str = Field(min_length=1, max_length=1000)
    status: IssueStatus
    plaintiff_position: str = Field(default="", max_length=4000)
    defendant_position: str = Field(default="", max_length=4000)
    confirmed_facts: list[IssueText] = Field(default_factory=list, max_length=30)
    unresolved_points: list[IssueText] = Field(default_factory=list, max_length=30)


class JudgeDecisionRequest(IntegrationModel):
    state_version: int = Field(ge=0)
    current_stage: str = Field(min_length=1, max_length=64)
    current_step: str = Field(
        min_length=2,
        max_length=64,
        pattern=r"^[A-Z][A-Z0-9-]+$",
    )
    trigger: TriggerType
    task: str = Field(min_length=1, max_length=2000)
    current_speaker: PartyRole | None = None
    allowed_actions: list[ActionType] = Field(default_factory=list, max_length=10)
    allowed_targets: list[PartyRole] = Field(default_factory=list, max_length=2)
    case_context: CaseContext
    stage_summaries: list[StageSummary] = Field(default_factory=list, max_length=12)
    recent_events: list[CourtEvent] = Field(default_factory=list, max_length=30)
    current_issue_id: str | None = Field(default=None, min_length=1, max_length=64)
    issues: list[CourtIssue] = Field(default_factory=list, max_length=20)

    @field_validator("allowed_actions")
    @classmethod
    def allowed_actions_must_be_unique(
        cls,
        value: list[ActionType],
    ) -> list[ActionType]:
        if len(value) != len(set(value)):
            raise ValueError("allowed_actions must not contain duplicates")
        return value

    @field_validator("allowed_targets")
    @classmethod
    def allowed_targets_must_be_unique(
        cls,
        value: list[PartyRole],
    ) -> list[PartyRole]:
        if len(value) != len(set(value)):
            raise ValueError("allowed_targets must not contain duplicates")
        return value

    @model_validator(mode="after")
    def actions_requiring_a_party_must_have_targets(self):
        party_actions = {
            ActionType.ASK_PARTY,
            ActionType.REQUEST_CLARIFICATION,
        }
        if party_actions.intersection(self.allowed_actions) and not self.allowed_targets:
            raise ValueError(
                "allowed_targets is required when a party-directed action is allowed"
            )
        issue_ids = [issue.issue_id for issue in self.issues]
        if len(issue_ids) != len(set(issue_ids)):
            raise ValueError("issue_id must be unique")
        if self.current_issue_id is not None and self.current_issue_id not in issue_ids:
            raise ValueError("current_issue_id must reference an issue in issues")
        return self


class JudgeSpeech(JudgeOutputModel):
    type: SpeechType = Field(description="Semantic type of the proposed speech.")
    text: str = Field(max_length=4000, description="Text that VirtualCourt may play.")
    target_role: PartyRole | None = Field(
        description="Target party for a question or clarification; otherwise null."
    )

    @model_validator(mode="after")
    def validate_text_and_target(self):
        targeted_types = {SpeechType.QUESTION, SpeechType.CLARIFICATION}
        if self.type == SpeechType.NONE and self.text:
            raise ValueError("speech text must be empty when type is NONE")
        if self.type != SpeechType.NONE and not self.text:
            raise ValueError("speech text is required unless type is NONE")
        if self.type in targeted_types and self.target_role is None:
            raise ValueError("target_role is required for question or clarification")
        if self.type not in targeted_types and self.target_role is not None:
            raise ValueError("target_role is only valid for question or clarification")
        return self


class JudgeActionProposal(JudgeOutputModel):
    type: ActionType = Field(description="The single proposed court action.")
    target_role: PartyRole | None = Field(
        description="Target party for a party-directed action; otherwise null."
    )

    @model_validator(mode="after")
    def validate_target(self):
        targeted_actions = {
            ActionType.ASK_PARTY,
            ActionType.REQUEST_CLARIFICATION,
        }
        if self.type in targeted_actions and self.target_role is None:
            raise ValueError("target_role is required for a party-directed action")
        if self.type not in targeted_actions and self.target_role is not None:
            raise ValueError("target_role is only valid for a party-directed action")
        return self


class LegalCitation(JudgeOutputModel):
    source: str = Field(min_length=1, max_length=512)
    article_no: str = Field(max_length=64)
    excerpt: str | None = Field(max_length=2000)


WarningText = Annotated[str, Field(min_length=1, max_length=500)]


class IssueAssessment(JudgeOutputModel):
    assessed_issue_id: str | None = Field(min_length=1, max_length=64)
    result: IssueAssessmentResult
    confirmed_facts: list[IssueText] = Field(max_length=30)
    unresolved_points: list[IssueText] = Field(max_length=30)
    next_issue_id: str | None = Field(min_length=1, max_length=64)

    @model_validator(mode="after")
    def validate_result_shape(self):
        if self.result == IssueAssessmentResult.NOT_APPLICABLE:
            if self.assessed_issue_id is not None or self.next_issue_id is not None:
                raise ValueError("NOT_APPLICABLE cannot reference an issue")
            if self.confirmed_facts or self.unresolved_points:
                raise ValueError("NOT_APPLICABLE cannot contain issue findings")
        elif self.assessed_issue_id is None:
            raise ValueError("assessed_issue_id is required for an issue assessment")

        if (
            self.result == IssueAssessmentResult.CONTINUE_DEBATE
            and not self.unresolved_points
        ):
            raise ValueError("CONTINUE_DEBATE requires unresolved_points")
        if (
            self.result != IssueAssessmentResult.READY_TO_CONFIRM
            and self.next_issue_id is not None
        ):
            raise ValueError("next_issue_id is only valid for READY_TO_CONFIRM")
        return self


class JudgeAgentOutput(JudgeOutputModel):
    """Exact JSON object the LLM must generate."""

    speech: JudgeSpeech
    action: JudgeActionProposal
    legal_citations: list[LegalCitation] = Field(max_length=20)
    confidence: ConfidenceLevel
    warnings: list[WarningText] = Field(max_length=20)
    issue_assessment: IssueAssessment

    @model_validator(mode="after")
    def validate_decision_consistency(self):
        if (
            self.action.target_role is not None
            and self.speech.target_role is not None
            and self.action.target_role != self.speech.target_role
        ):
            raise ValueError("speech and action must target the same party")

        if (
            self.speech.type == SpeechType.LEGAL_EXPLANATION
            and not self.legal_citations
            and self.confidence != ConfidenceLevel.INSUFFICIENT
        ):
            raise ValueError(
                "a legal explanation without citations must have INSUFFICIENT confidence"
            )
        if self.confidence == ConfidenceLevel.INSUFFICIENT and not self.warnings:
            raise ValueError("INSUFFICIENT confidence requires at least one warning")

        expected_speech_types = {
            ActionType.ASK_PARTY: SpeechType.QUESTION,
            ActionType.REQUEST_CLARIFICATION: SpeechType.CLARIFICATION,
            ActionType.SUMMARIZE: SpeechType.SUMMARY,
        }
        expected_speech_type = expected_speech_types.get(self.action.type)
        if expected_speech_type is not None and self.speech.type != expected_speech_type:
            raise ValueError(
                f"{self.action.type} requires {expected_speech_type} speech"
            )

        expected_action_types = {
            SpeechType.QUESTION: ActionType.ASK_PARTY,
            SpeechType.CLARIFICATION: ActionType.REQUEST_CLARIFICATION,
            SpeechType.SUMMARY: ActionType.SUMMARIZE,
            SpeechType.LEGAL_EXPLANATION: ActionType.NO_ACTION,
        }
        expected_action_type = expected_action_types.get(self.speech.type)
        if expected_action_type is not None and self.action.type != expected_action_type:
            raise ValueError(
                f"{self.speech.type} speech requires {expected_action_type} action"
            )
        return self


class JudgeDecisionResponse(JudgeAgentOutput):
    """Public API response after the service injects the request state version."""

    state_version: int = Field(ge=0)


def judge_agent_output_json_schema() -> dict:
    """Return the JSON Schema supplied to the model for structured output."""

    return JudgeAgentOutput.model_json_schema(mode="validation")
